<?php
/**
 * @file
 * Library loader for the Defuse PHP-encryption library.
 */


/**
 * Implements hook_libraries_info().
 */
function real_aes_libraries_info() {
  return array(
    'php-encryption' => array(
      'name' => t('Defuse PHP-encryption'),
      'vendor_url' => 'https://github.com/defuse/php-encryption',
      'download_url' => 'https://github.com/defuse/php-encryption/archive/master.zip',
      'files' => array(
        'php' => array('autoload.php'),
      ),
      'version' => 'master',
    ),
  );
}
